source "https://rubygems.org"

gem "jekyll", "4.3.3"

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.16.5"
  gem 'jekyll-tagging', "1.1.0"
  gem "jekyll-sitemap", "1.4.0"
  gem "jekyll-feed", "0.17.0"
  gem "jekyll-seo-tag", "2.8.0"
end
