title: Frank De Graeve
description: >-
  DesignOps · UX Strategy · AI Adoption | Helping teams build the conditions to scale design impact and AI fluency.
social_media_share_image: /images/01.jpg
disqus-identifier:
google-analytics: